// This file is auto-generated by emoji_converter.py. Do not edit directly.
#pragma once
#include <stdint.h>
#include <stddef.h>

struct BuiltinEmoji {
    uint32_t code;
    const uint8_t* bitmap; // 12x12 monochrome XBM format bitmap
};

extern const BuiltinEmoji BUILTIN_EMOJIS[];
extern const size_t BUILTIN_EMOJIS_NUM;

// Returns 12x12 monochrome XBM bitmap if found, otherwise nullptr
const uint8_t* builtin_emoji_lookup(uint32_t code);
