import os
import re
from PIL import Image

def otsu_threshold(lums):
    best_thresh = 128
    best_variance = -1
    min_l = int(min(lums))
    max_l = int(max(lums))
    if max_l - min_l <= 2:
        return min_l
    for t in range(min_l + 1, max_l):
        left = [x for x in lums if x < t]
        right = [x for x in lums if x >= t]
        if not left or not right:
            continue
        w0 = len(left) / len(lums)
        w1 = len(right) / len(lums)
        mean0 = sum(left) / len(left)
        mean1 = sum(right) / len(right)
        variance = w0 * w1 * ((mean0 - mean1) ** 2)
        if variance > best_variance:
            best_variance = variance
            best_thresh = t
    return best_thresh

def process_emoji(png_path, target_size=(12, 12)):
    # Load PNG
    try:
        img = Image.open(png_path)
    except Exception as e:
        print(f"Error opening {png_path}: {e}")
        return None

    if img.mode != 'RGBA':
        img = img.convert('RGBA')
    
    if img.size != target_size:
        try:
            resample = Image.Resampling.LANCZOS
        except AttributeError:
            resample = Image.ANTIALIAS
        img = img.resize(target_size, resample=resample)
        
    pix = img.load()
    
    width, height = target_size
    opaque_lums = []
    for y in range(height):
        for x in range(width):
            r, g, b, a = pix[x, y]
            if a >= 128:
                lum = 0.299 * r + 0.587 * g + 0.114 * b
                opaque_lums.append(lum)
                
    if not opaque_lums:
        return [0] * ((width + 7) // 8 * height)
        
    min_lum = min(opaque_lums)
    max_lum = max(opaque_lums)
    contrast = max_lum - min_lum
    
    use_alpha_mask = False
    if contrast < 80:
        use_alpha_mask = True
    else:
        # Dynamically compute threshold using Otsu's binarisation
        threshold = otsu_threshold(opaque_lums)
        
    xbm_bytes = []
    byte_width = (width + 7) // 8
    
    for y in range(height):
        byte_val = 0
        for x in range(width):
            r, g, b, a = pix[x, y]
            is_fg = False
            if a >= 128:
                if use_alpha_mask:
                    is_fg = True
                else:
                    # Check if it is a boundary pixel of the opaque shape (silhouette outline)
                    is_boundary = False
                    for dx, dy in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                        nx, ny = x + dx, y + dy
                        if 0 <= nx < width and 0 <= ny < height:
                            _, _, _, na = pix[nx, ny]
                            if na < 128:
                                is_boundary = True
                                break
                        else:
                            is_boundary = True
                            break
                    
                    if is_boundary:
                        is_fg = True
                    else:
                        lum = 0.299 * r + 0.587 * g + 0.114 * b
                        is_fg = (lum < threshold)
            
            bit_idx = x % 8
            if is_fg:
                byte_val |= (1 << bit_idx)
            
            if bit_idx == 7 or x == width - 1:
                xbm_bytes.append(byte_val)
                byte_val = 0
                
    return xbm_bytes

def main():
    emoji_dir = "/Users/t-miura/prog/plai"
    # Find emoji directory inside the workspace
    if os.path.exists(os.path.join(emoji_dir, "emoji")):
        emoji_dir = os.path.join(emoji_dir, "emoji")
        
    output_cpp = "/Users/t-miura/prog/plai/main/hal/builtin_emojis.cpp"
    output_h = "/Users/t-miura/prog/plai/main/hal/builtin_emojis.h"
    
    pattern = re.compile(r"^u([0-9A-Fa-f]+)\.png$")
    
    emoji_files = []
    for f in os.listdir(emoji_dir):
        m = pattern.match(f)
        if m:
            code_str = m.group(1)
            code = int(code_str, 16)
            emoji_files.append((code, f))
            
    emoji_files.sort()
    
    print(f"Found {len(emoji_files)} single-codepoint emoji PNG files to convert.")
    
    cpp_lines = [
        '// This file is auto-generated by emoji_converter.py. Do not edit directly.',
        '#include "builtin_emojis.h"',
        '#include <esp_attr.h>',
        '',
    ]
    
    for code, filename in emoji_files:
        png_path = os.path.join(emoji_dir, filename)
        xbm_bytes = process_emoji(png_path)
        if xbm_bytes is None:
            continue
        byte_strs = [f"0x{b:02X}" for b in xbm_bytes]
        cpp_lines.append(f"static const uint8_t emoji_{code:X}[] = {{{', '.join(byte_strs)}}};")
        
    cpp_lines.append("")
    cpp_lines.append("const BuiltinEmoji BUILTIN_EMOJIS[] = {")
    for code, _ in emoji_files:
        cpp_lines.append(f"    {{ 0x{code:X}, emoji_{code:X} }},")
    cpp_lines.append("};")
    cpp_lines.append("")
    cpp_lines.append("const size_t BUILTIN_EMOJIS_NUM = sizeof(BUILTIN_EMOJIS) / sizeof(BUILTIN_EMOJIS[0]);")
    cpp_lines.append("")
    
    cpp_lines.extend([
        "const uint8_t* builtin_emoji_lookup(uint32_t code) {",
        "    if (BUILTIN_EMOJIS_NUM == 0) return nullptr;",
        "    size_t low = 0;",
        "    size_t high = BUILTIN_EMOJIS_NUM - 1;",
        "    while (low <= high) {",
        "        size_t mid = low + (high - low) / 2;",
        "        if (BUILTIN_EMOJIS[mid].code == code) {",
        "            return BUILTIN_EMOJIS[mid].bitmap;",
        "        } else if (BUILTIN_EMOJIS[mid].code < code) {",
        "            low = mid + 1;",
        "        } else {",
        "            if (mid == 0) break;",
        "            high = mid - 1;",
        "        }",
        "    }",
        "    return nullptr;",
        "}",
    ])
    
    with open(output_cpp, "w") as f:
        f.write("\n".join(cpp_lines) + "\n")
        
    h_content = """// This file is auto-generated by emoji_converter.py. Do not edit directly.
#pragma once
#include <stdint.h>
#include <stddef.h>

struct BuiltinEmoji {
    uint32_t code;
    const uint8_t* bitmap; // 12x12 monochrome XBM format bitmap
};

extern const BuiltinEmoji BUILTIN_EMOJIS[];
extern const size_t BUILTIN_EMOJIS_NUM;

// Returns 12x12 monochrome XBM bitmap if found, otherwise nullptr
const uint8_t* builtin_emoji_lookup(uint32_t code);
"""
    with open(output_h, "w") as f:
        f.write(h_content)
        
    print("Generation complete!")

if __name__ == "__main__":
    main()
